name: assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - blast=2.13.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - circos=0.69.8
  - curl=7.83.1
  - cycler=0.11.0
  - entrez-direct=16.2
  - expat=2.4.8
  - fastp=0.23.2
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - giflib=5.2.1
  - glimmerhmm=3.0.4
  - icu=70.1
  - isa-l=2.30.0
  - joblib=1.1.0
  - jpeg=9e
  - k8=0.2.5
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp=1.2.3
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-meta=7.0.0
  - lz4-c=1.9.3
  - matplotlib-base=3.5.2
  - minimap2=2.24
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.23.1
  - openjdk=11.0.1
  - openjpeg=2.4.0
  - openmp=7.0.0
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-autoloader=5.74
  - perl-carp=1.50
  - perl-clone=0.42
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-config-general=2.65
  - perl-digest-perl-md5=1.9
  - perl-dynaloader=1.25
  - perl-encode=3.18
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.64
  - perl-font-ttf=1.06
  - perl-gd=2.76
  - perl-io-compress=2.106
  - perl-io-string=1.08
  - perl-io-zlib=1.11
  - perl-json=4.07
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-math-bezier=0.01
  - perl-math-round=0.07
  - perl-math-vecstat=0.08
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-number-format=1.75
  - perl-params-validate=1.30
  - perl-parent=0.238
  - perl-pathtools=3.75
  - perl-readonly=2.05
  - perl-regexp-common=2017060201
  - perl-scalar-list-utils=1.62
  - perl-set-intspan=1.19
  - perl-statistics-basic=1.6611
  - perl-svg=2.87
  - perl-text-format=0.62
  - perl-time-hires=1.9764
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-xml-parser=2.44_01
  - pillow=9.2.0
  - pip=22.2.1
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.9.0
  - python-dateutil=2.8.2
  - python_abi=3.9
  - quast=5.2.0
  - readline=8.1.2
  - setuptools=63.2.0
  - simplejson=3.17.6
  - six=1.16.0
  - spades=3.15.5
  - sqlite=3.39.2
  - sysroot_linux-64=2.17
  - tk=8.6.12
  - trimmomatic=0.39
  - tzdata=2022a
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
prefix: /home/egonozer/miniconda3/envs/assembly
